# coding: utf-8

"""
    Workout Tracker API

    API for managing workout plans, tracking exercises, and monitoring fitness progress

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ApiV1UsersUserIdPlansPostRequest(BaseModel):
    """
    ApiV1UsersUserIdPlansPostRequest
    """ # noqa: E501
    split: StrictStr
    workout_type: StrictStr = Field(alias="workoutType")
    days_per_week: Annotated[int, Field(le=7, strict=True, ge=1)] = Field(alias="daysPerWeek")
    weeks: Annotated[int, Field(strict=True, ge=1)]
    start_date: date = Field(alias="startDate")
    __properties: ClassVar[List[str]] = ["split", "workoutType", "daysPerWeek", "weeks", "startDate"]

    @field_validator('workout_type')
    def workout_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('calisthenics', 'gym',):
            raise ValueError("must be one of enum values ('calisthenics', 'gym')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiV1UsersUserIdPlansPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ApiV1UsersUserIdPlansPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "split": obj.get("split"),
            "workoutType": obj.get("workoutType"),
            "daysPerWeek": obj.get("daysPerWeek"),
            "weeks": obj.get("weeks"),
            "startDate": obj.get("startDate")
        })
        return _obj


