# coding: utf-8

"""
    Workout Tracker API

    API for managing workout plans, tracking exercises, and monitoring fitness progress

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.exercise_progress_personal_records import ExerciseProgressPersonalRecords
from openapi_server.models.exercise_progress_progression_inner import ExerciseProgressProgressionInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ExerciseProgress(BaseModel):
    """
    ExerciseProgress
    """ # noqa: E501
    exercise_id: Optional[StrictStr] = Field(default=None, alias="exerciseId")
    exercise_name: Optional[StrictStr] = Field(default=None, alias="exerciseName")
    first_recorded: Optional[date] = Field(default=None, alias="firstRecorded")
    last_recorded: Optional[date] = Field(default=None, alias="lastRecorded")
    total_sessions: Optional[StrictInt] = Field(default=None, alias="totalSessions")
    progression: Optional[List[ExerciseProgressProgressionInner]] = None
    personal_records: Optional[ExerciseProgressPersonalRecords] = Field(default=None, alias="personalRecords")
    __properties: ClassVar[List[str]] = ["exerciseId", "exerciseName", "firstRecorded", "lastRecorded", "totalSessions", "progression", "personalRecords"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExerciseProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in progression (list)
        _items = []
        if self.progression:
            for _item in self.progression:
                if _item:
                    _items.append(_item.to_dict())
            _dict['progression'] = _items
        # override the default output from pydantic by calling `to_dict()` of personal_records
        if self.personal_records:
            _dict['personalRecords'] = self.personal_records.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ExerciseProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exerciseId": obj.get("exerciseId"),
            "exerciseName": obj.get("exerciseName"),
            "firstRecorded": obj.get("firstRecorded"),
            "lastRecorded": obj.get("lastRecorded"),
            "totalSessions": obj.get("totalSessions"),
            "progression": [ExerciseProgressProgressionInner.from_dict(_item) for _item in obj.get("progression")] if obj.get("progression") is not None else None,
            "personalRecords": ExerciseProgressPersonalRecords.from_dict(obj.get("personalRecords")) if obj.get("personalRecords") is not None else None
        })
        return _obj


