# coding: utf-8

"""
    Workout Tracker API

    API for managing workout plans, tracking exercises, and monitoring fitness progress

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ExerciseDetail(BaseModel):
    """
    ExerciseDetail
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    target_muscle: Optional[StrictStr] = Field(default=None, alias="targetMuscle")
    equipment: Optional[StrictStr] = None
    difficulty: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    instructions: Optional[List[StrictStr]] = None
    video_url: Optional[StrictStr] = Field(default=None, alias="videoUrl")
    image_url: Optional[StrictStr] = Field(default=None, alias="imageUrl")
    tips: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "type", "targetMuscle", "equipment", "difficulty", "description", "instructions", "videoUrl", "imageUrl", "tips"]

    @field_validator('difficulty')
    def difficulty_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('beginner', 'intermediate', 'advanced',):
            raise ValueError("must be one of enum values ('beginner', 'intermediate', 'advanced')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExerciseDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ExerciseDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "targetMuscle": obj.get("targetMuscle"),
            "equipment": obj.get("equipment"),
            "difficulty": obj.get("difficulty"),
            "description": obj.get("description"),
            "instructions": obj.get("instructions"),
            "videoUrl": obj.get("videoUrl"),
            "imageUrl": obj.get("imageUrl"),
            "tips": obj.get("tips")
        })
        return _obj


