# coding: utf-8

"""
    Workout Tracker API

    API for managing workout plans, tracking exercises, and monitoring fitness progress

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ExerciseListExercisesInner(BaseModel):
    """
    ExerciseListExercisesInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = Field(default=None, alias="imageUrl")
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    target_muscles: Optional[List[StrictStr]] = Field(default=None, alias="targetMuscles")
    max_weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="User's max weight if they've performed this exercise", alias="maxWeight")
    __properties: ClassVar[List[str]] = ["id", "imageUrl", "name", "type", "targetMuscles", "maxWeight"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExerciseListExercisesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ExerciseListExercisesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "imageUrl": obj.get("imageUrl"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "targetMuscles": obj.get("targetMuscles"),
            "maxWeight": obj.get("maxWeight")
        })
        return _obj


